<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-HR6DLCF" ignored="1" name="Multi users Login attempts" tests="30" failures="2" timestamp="07 Aug 2017 05:10:55 GMT" time="30.197" errors="0">
  <testcase name="LoadBrowser" time="0.001" classname="all_operations.Browser_Config"/>
  <testcase name="LoadBrowser" time="6.37" classname="all_operations.Browser_Config"/>
  <testcase name="load_url" time="1.293" classname="all_operations.Browser_Config"/>
  <testcase name="Test_Login" time="0.015" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="0.119" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="2.008" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="0.202" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="2.009" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="0.165" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="1.266" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="2.012" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="1.55" classname="test_cases.Login_Test">
    <failure type="java.lang.AssertionError" message="expected [https://fmlcb.shaalmi.pk/admin/dashboard] but found [https://fmlcb.shaalmi.pk/login]">
      <![CDATA[java.lang.AssertionError: expected [https://fmlcb.shaalmi.pk/admin/dashboard] but found [https://fmlcb.shaalmi.pk/login]
	at all_operations.General_Operations.Hybrid_Ops(General_Operations.java:75)
	at test_cases.Login_Test.Test_Login(Login_Test.java:22)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test_Login -->
  <testcase name="Test_Login" time="0.12" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="0.024" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="0.066" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="0.041" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="2.008" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="0.856" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="2.006" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="1.544" classname="test_cases.Login_Test">
    <failure type="java.lang.AssertionError" message="expected [https://fmlcb.shaalmi.pk/admin/dashboard] but found [https://fmlcb.shaalmi.pk/login]">
      <![CDATA[java.lang.AssertionError: expected [https://fmlcb.shaalmi.pk/admin/dashboard] but found [https://fmlcb.shaalmi.pk/login]
	at all_operations.General_Operations.Hybrid_Ops(General_Operations.java:75)
	at test_cases.Login_Test.Test_Login(Login_Test.java:22)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- Test_Login -->
  <testcase name="Test_Login" time="0.146" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="0.026" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="0.062" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="0.04" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="2.007" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="0.967" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="1.553" classname="test_cases.Login_Test"/>
  <testcase name="Test_LogOut" time="0.013" classname="test_cases.Logout_Test"/>
  <testcase name="Test_LogOut" time="0.277" classname="test_cases.Logout_Test"/>
  <testcase name="Test_LogOut" time="1.166" classname="test_cases.Logout_Test"/>
  <testcase name="Test_Login_Admin" time="0.0" classname="test_cases.Login_Test">
    <ignored/>
  </testcase> <!-- Test_Login_Admin -->
</testsuite> <!-- Multi users Login attempts -->
