<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-HR6DLCF" name="test_cases.Login_Test" tests="30" failures="2" timestamp="20 Aug 2017 12:56:50 GMT" time="76.484" errors="0">
  <testcase name="Test_Login" time="0.215" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="3.098" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="0.463" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login_Admin" time="2.124" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="0.254" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="0.417" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="0.648" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="0.301" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="1.375" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login_Admin" time="1.116" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="0.362" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="1.716" classname="test_cases.Login_Test">
    <failure type="java.lang.AssertionError" message="Invalid parameter:Assert match failed for https://fmlcb.shaalmi.pk/admin/dashboardand foundhttps://fmlcb.shaalmi.pk/login expected [https://fmlcb.shaalmi.pk/admin/dashboard] but found [https://fmlcb.shaalmi.pk/login]">
      <![CDATA[java.lang.AssertionError: Invalid parameter:Assert match failed for https://fmlcb.shaalmi.pk/admin/dashboardand foundhttps://fmlcb.shaalmi.pk/login expected [https://fmlcb.shaalmi.pk/admin/dashboard] but found [https://fmlcb.shaalmi.pk/login]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at all_operations.General_Operations.Hybrid_Ops(General_Operations.java:76)
	at test_cases.Login_Test.Test_Login(Login_Test.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- Test_Login -->
  <testcase name="Test_Login_Admin" time="0.003" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="2.004" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="1.660" classname="test_cases.Login_Test">
    <failure type="java.lang.AssertionError" message="Invalid parameter:Assert match failed for https://fmlcb.shaalmi.pk/admin/dashboardand foundhttps://fmlcb.shaalmi.pk/login expected [https://fmlcb.shaalmi.pk/admin/dashboard] but found [https://fmlcb.shaalmi.pk/login]">
      <![CDATA[java.lang.AssertionError: Invalid parameter:Assert match failed for https://fmlcb.shaalmi.pk/admin/dashboardand foundhttps://fmlcb.shaalmi.pk/login expected [https://fmlcb.shaalmi.pk/admin/dashboard] but found [https://fmlcb.shaalmi.pk/login]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at all_operations.General_Operations.Hybrid_Ops(General_Operations.java:76)
	at test_cases.Login_Test.Test_Login(Login_Test.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- Test_Login -->
  <testcase name="Test_Login_Admin" time="0.527" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login_Admin" time="1.549" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="2.027" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="2.708" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="1.641" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login_Admin" time="10.349" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="0.875" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="2.018" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="8.600" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="0.290" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="0.300" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="0.000" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login" time="11.471" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login_Admin" time="1.608" classname="test_cases.Login_Test"/>
  <testcase name="Test_Login_Admin" time="16.765" classname="test_cases.Login_Test"/>
</testsuite> <!-- test_cases.Login_Test -->
